#!/usr/bin/env bash
# Lee YEARPLAN_AUTH_* de .env y genera basic auth para Caddy (y .htpasswd para nginx).
set -euo pipefail

DEPLOY_PATH="${DEPLOY_PATH:-/opt/yearplan.sermestre.es}"
ENV_FILE="${DEPLOY_PATH}/.env"
CADDY_FRAGMENT="${DEPLOY_PATH}/deploy/caddy.d/10-basicauth.caddy"
HTPASSWD_FILE="${DEPLOY_PATH}/deploy/.htpasswd"

hash_password() {
  local user="$1"
  local pass="$2"
  if command -v caddy >/dev/null 2>&1; then
    caddy hash-password --plaintext "${pass}"
    return
  fi
  if command -v htpasswd >/dev/null 2>&1; then
    htpasswd -nbB "${user}" "${pass}" | cut -d: -f2-
    return
  fi
  echo "ERROR: need 'caddy' or 'htpasswd' (apache2-utils) to hash the password." >&2
  exit 1
}

disable_auth() {
  rm -f "${CADDY_FRAGMENT}" "${HTPASSWD_FILE}"
  echo "[auth] No password configured — site stays public."
}

mkdir -p "${DEPLOY_PATH}/deploy/caddy.d"

if [[ ! -f "${ENV_FILE}" ]]; then
  disable_auth
  exit 0
fi

# shellcheck disable=SC1090
set -a
source "${ENV_FILE}"
set +a

AUTH_USER="${YEARPLAN_AUTH_USER:-}"
AUTH_PASS="${YEARPLAN_AUTH_PASSWORD:-}"

if [[ -z "${AUTH_USER}" || -z "${AUTH_PASS}" ]]; then
  disable_auth
  exit 0
fi

HASH="$(hash_password "${AUTH_USER}" "${AUTH_PASS}")"

cat > "${CADDY_FRAGMENT}" <<EOF
# Generated by scripts/sync-site-auth.sh — do not edit
basicauth /* {
	${AUTH_USER} ${HASH}
}
EOF
chmod 640 "${CADDY_FRAGMENT}"

# nginx (deploy/nginx-yearplan.sermestre.es.conf) usa este fichero si lo activas
if command -v htpasswd >/dev/null 2>&1; then
  htpasswd -nbB "${AUTH_USER}" "${AUTH_PASS}" > "${HTPASSWD_FILE}"
  chmod 640 "${HTPASSWD_FILE}"
fi

echo "[auth] Password protection enabled for user '${AUTH_USER}'."
